name_or_path: /science/llms/gemma-2-9b-it
name: gemma-2
model_vec_size: 17920
class_name: AutoModelForCausalLM
edit_modules:
# - model.layers.6.mlp.down_proj
# - model.layers.7.mlp.down_proj
# - model.layers.8.mlp.down_proj
# - model.layers.9.mlp.down_proj
# - model.layers.10.mlp.down_proj
# - model.layers.11.mlp.down_proj
# - model.layers.12.mlp.down_proj
# - model.layers.13.mlp.down_proj
# - model.layers.14.mlp.down_proj
# - model.layers.15.mlp.down_proj
# - model.layers.16.mlp.down_proj
# - model.layers.17.mlp.down_proj
# - model.layers.18.mlp.down_proj
# - model.layers.19.mlp.down_proj
# - model.layers.20.mlp.down_proj
# - model.layers.21.mlp.down_proj
# - model.layers.22.mlp.down_proj
# - model.layers.23.mlp.down_proj
# - model.layers.24.mlp.down_proj
# - model.layers.25.mlp.down_proj
# - model.layers.26.mlp.down_proj
# - model.layers.27.mlp.down_proj
# - model.layers.28.mlp.down_proj
# - model.layers.29.mlp.down_proj
# - model.layers.30.mlp.down_proj
# - model.layers.31.mlp.down_proj
# - model.layers.32.mlp.down_proj
# - model.layers.33.mlp.down_proj
# - model.layers.34.mlp.down_proj
# - model.layers.35.mlp.down_proj
# - model.layers.36.mlp.down_proj
# - model.layers.37.mlp.down_proj
# - model.layers.38.mlp.down_proj
# - model.layers.39.mlp.down_proj
# - model.layers.40.mlp.down_proj
# - model.layers.41.mlp.down_proj
# ###############################
# - model.layers.22.mlp.gate_proj
# - model.layers.23.mlp.gate_proj
# - model.layers.24.mlp.gate_proj
# - model.layers.25.mlp.gate_proj
# - model.layers.26.mlp.gate_proj
# - model.layers.27.mlp.gate_proj
# - model.layers.28.mlp.gate_proj
# - model.layers.29.mlp.gate_proj
# - model.layers.30.mlp.gate_proj
# - model.layers.31.mlp.gate_proj
- model.layers.32.mlp.gate_proj
- model.layers.33.mlp.gate_proj
- model.layers.34.mlp.gate_proj
- model.layers.35.mlp.gate_proj
- model.layers.36.mlp.gate_proj
- model.layers.37.mlp.gate_proj
- model.layers.38.mlp.gate_proj
- model.layers.39.mlp.gate_proj
- model.layers.40.mlp.gate_proj
# - model.layers.41.mlp.gate_proj
###############################
# - model.layers.12.mlp.up_proj
# - model.layers.13.mlp.up_proj
# - model.layers.14.mlp.up_proj
# - model.layers.15.mlp.up_proj
# - model.layers.16.mlp.up_proj
# - model.layers.17.mlp.up_proj
# - model.layers.18.mlp.up_proj
# - model.layers.19.mlp.up_proj
# - model.layers.20.mlp.up_proj
# - model.layers.21.mlp.up_proj
# - model.layers.22.mlp.up_proj
# - model.layers.23.mlp.up_proj
# - model.layers.24.mlp.up_proj
# - model.layers.25.mlp.up_proj
# - model.layers.26.mlp.up_proj
# - model.layers.27.mlp.up_proj
# - model.layers.28.mlp.up_proj
# - model.layers.29.mlp.up_proj
# - model.layers.30.mlp.up_proj
# - model.layers.31.mlp.up_proj
- model.layers.32.mlp.up_proj
- model.layers.33.mlp.up_proj
- model.layers.34.mlp.up_proj
- model.layers.35.mlp.up_proj
- model.layers.36.mlp.up_proj
- model.layers.37.mlp.up_proj
- model.layers.38.mlp.up_proj
- model.layers.39.mlp.up_proj
- model.layers.40.mlp.up_proj
# - model.layers.41.mlp.up_proj

half: True