name_or_path: /data/llms/Meta-Llama-3-8B-Instruct
name: llama-3-instruct
model_vec_size: 18432
class_name: AutoModelForCausalLM
edit_modules:
# - model.layers.4.mlp.down_proj
# - model.layers.5.mlp.down_proj
# - model.layers.6.mlp.down_proj
# - model.layers.7.mlp.down_proj
# - model.layers.8.mlp.down_proj
# - model.layers.9.mlp.down_proj
# - model.layers.10.mlp.down_proj
# - model.layers.11.mlp.down_proj
# - model.layers.12.mlp.down_proj
# - model.layers.13.mlp.down_proj
# - model.layers.14.mlp.down_proj
# - model.layers.15.mlp.down_proj
# - model.layers.16.mlp.down_proj
# - model.layers.17.mlp.down_proj
# - model.layers.18.mlp.down_proj
# - model.layers.19.mlp.down_proj
# - model.layers.20.mlp.down_proj
# - model.layers.21.mlp.down_proj
# - model.layers.22.mlp.down_proj
# - model.layers.23.mlp.down_proj
# - model.layers.24.mlp.down_proj
# - model.layers.25.mlp.down_proj
# - model.layers.26.mlp.down_proj
# - model.layers.27.mlp.down_proj
# - model.layers.28.mlp.down_proj
# - model.layers.29.mlp.down_proj
# - model.layers.30.mlp.down_proj
# ###############################
# - model.layers.8.mlp.gate_proj
# - model.layers.9.mlp.gate_proj
# - model.layers.10.mlp.gate_proj

- model.layers.11.mlp.gate_proj
- model.layers.12.mlp.gate_proj
- model.layers.13.mlp.gate_proj
- model.layers.14.mlp.gate_proj
- model.layers.15.mlp.gate_proj

# - model.layers.16.mlp.gate_proj
# - model.layers.17.mlp.gate_proj
# - model.layers.18.mlp.gate_proj
# - model.layers.19.mlp.gate_proj
# - model.layers.20.mlp.gate_proj
# - model.layers.21.mlp.gate_proj
# - model.layers.22.mlp.gate_proj
# - model.layers.23.mlp.gate_proj
# - model.layers.24.mlp.gate_proj
# - model.layers.25.mlp.gate_proj
# - model.layers.26.mlp.gate_proj
# - model.layers.27.mlp.gate_proj
# - model.layers.28.mlp.gate_proj
# - model.layers.29.mlp.gate_proj
# - model.layers.30.mlp.gate_proj
# - model.layers.31.mlp.gate_proj
###############################
# - model.layers.12.mlp.up_proj
# - model.layers.13.mlp.up_proj
# - model.layers.14.mlp.up_proj
# - model.layers.15.mlp.up_proj
# - model.layers.16.mlp.up_proj
# - model.layers.17.mlp.up_proj

- model.layers.18.mlp.up_proj
- model.layers.19.mlp.up_proj
- model.layers.20.mlp.up_proj
- model.layers.21.mlp.up_proj

- model.layers.22.mlp.up_proj
- model.layers.23.mlp.up_proj
- model.layers.24.mlp.up_proj

# - model.layers.25.mlp.up_proj
# - model.layers.26.mlp.up_proj
# - model.layers.27.mlp.up_proj
# - model.layers.28.mlp.up_proj
# - model.layers.29.mlp.up_proj
# - model.layers.30.mlp.up_proj
# - model.layers.31.mlp.up_proj

half: True